--- 

- name : "mount md0 harddrive"
  ansible.posix.mount:
    path: UUID=e3c6d63f-9105-4b12-82f3-91947ab1a565
    src: /dev/disk0
    fstype: ext4
    opts: defaults
    state: present

- name : "mount md2 harddrive"
  ansible.posix.mount:
    path: UUID=ca233860-2ba8-483d-a0e3-868e02c56bec
    src: /dev/disk1
    fstype: ext4
    opts: defaults
    state: present

- name : "mount sda1 harddrive"
  ansible.posix.mount:
    path: /media/big
    src: UUID=b365daec-de01-4e3a-9d0c-f91e7748f0ac
    fstype: btrfs
    opts: defaults
    state: present

- name: "change dns server add 9.9.9.9 DNS"
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 9.9.9.9"
    state: present

- name: "remove default dns server"
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 192.168.1.254"
    state: absent
